export const DEARLY_DATA = {
  daily: [
    "You don't have to earn your rest. Some days, simply existing is the most courageous thing you can do.",
    "The version of you from a year ago would be so proud of how far you've come, even quietly.",
    "You are allowed to want things: gentle things, big things, complicated things. All of it counts.",
    "Not every day needs to be productive. Some days are just for being alive, and that's enough.",
    "Your softness is not a weakness. It takes real strength to stay tender in a world that doesn't always deserve it.",
    "It is okay to change your mind about who you want to be. You are the only person who has to live in your life.",
    "Slow progress is still progress. You aren't falling behind just because you're taking your time.",
    "Most of your growth happens when nobody is looking, including you. That doesn't make it any less real.",
    "Notice the small things that went right today. Sometimes they are the only things that actually matter.",
  ],
  birthday: [
    "Another year of being entirely, wonderfully yourself. That's worth celebrating slowly.",
    "May this year hold something that surprises you in the best way, the kind you didn't think to wish for.",
    "You've made it through every hard day so far. Here's to the soft ones waiting ahead.",
    "There is no rush to figure out the next decade today. Just be here, in this specific year, for a while.",
    "You are allowed to take up space. This year, try to stop apologizing for it.",
    "Getting older is just another way of saying you survived a lot of things. Be proud of that.",
  ],
  graduation: [
    "You didn't just finish something; you became someone new in the process. Notice that.",
    "The world is a little better for having one more person in it who worked this hard.",
    "Whatever comes next, you already know how to begin again. You've done it before.",
    "You don't need to have the whole map yet. Just worry about the next few steps in front of you.",
    "Your degree is just paper. The way you didn't quit when things got heavy is the real story.",
  ],
  'hard day': [
    "You're allowed to be not okay right now. You don't have to dress it up or explain it.",
    "Some days are just for surviving, and surviving is still something.",
    "This feeling is not permanent. You've felt other things before, and you will again.",
    "If all you did today was carry the weight of your own heart, you've done enough.",
    "Sometimes the best thing you can do for yourself is go to sleep and try again tomorrow.",
    "Be as patient with yourself as you would be with a friend. You deserve that same grace.",
  ],
}